### ISSUE TITLE
Add command line switches to conan install

### ISSUE THREAD

**Issue by rockdreamer** [claremacrae/googletest-starter-project#1]
https://github.com/claremacrae/googletest-starter-project/blob/b8ccf1545728a7b80be7aac71f390aca6089177e/build-win32.bat#L3

http://docs.conan.io/en/latest/reference/generators/visualstudio.html

Cheers!

**Comment by claremacrae** [comment]
Thanks. I was generating using cmake - switching to generator `visual_studio_multi` ought to get me sorted - except that following the instructions I still haven't worked out how to apply to the generated property files to a newly-created solution....

For now, I wrote that up in conan-io/docs#556

**Comment by claremacrae** [comment]
So I learned in https://github.com/conan-io/docs/issues/556 that if I am machine-generating .sln files with cmake, I don't need to use `visual_studio_multi` - and `cmake_multi` is the way to go.

For my reference, this is what I was using when running `visual_studio_multi`

```
REM  Maybe add -s compiler.version=15 ?
conan install . -g visual_studio_multi -s arch=x86    -s build_type=Debug
conan install . -g visual_studio_multi -s arch=x86_64 -s build_type=Debug
conan install . -g visual_studio_multi -s arch=x86    -s build_type=Release
conan install . -g visual_studio_multi -s arch=x86_64 -s build_type=Release
```

**Comment by claremacrae** [comment]
The answer was to use the `cmake_multi` generator - and also to adjust the CMake instructions for libraries to line against - using `conan_target_link_libraries` - see
http://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html
