### ISSUE TITLE
Fix linker errors in Visual Studio

### ISSUE THREAD

**Issue by claremacrae** [claremacrae/googletest-starter-project#2]
```
2>main.obj : error LNK2019: unresolved external symbol "public: static class testing::UnitTest * __cdecl testing::UnitTest::GetInstance(void)" (?GetInstance@UnitTest@testing@@SAPEAV12@XZ) referenced in function "int __cdecl RUN_ALL_TESTS(void)" (?RUN_ALL_TESTS@@YAHXZ)
2>main.obj : error LNK2019: unresolved external symbol "public: int __cdecl testing::UnitTest::Run(void)" (?Run@UnitTest@testing@@QEAAHXZ) referenced in function "int __cdecl RUN_ALL_TESTS(void)" (?RUN_ALL_TESTS@@YAHXZ)
2>main.obj : error LNK2019: unresolved external symbol "void __cdecl testing::InitGoogleTest(int *,char * *)" (?InitGoogleTest@testing@@YAXPEAHPEAPEAD@Z) referenced in function main
2>C:\Users\Clare\Documents\Programming\GitHub\googletest-starter-project\build-windows\tests\Debug\tests.exe : fatal error LNK1120: 3 unresolved externals
```

**Comment by claremacrae** [comment]
To reproduce the problem:
1. Clone the repo at https://github.com/claremacrae/googletest-starter-project/commit/67878c155fe8637e1659783e5f67021e224e70a7
2. cd to the source directory
3. run `configure_vs.bat`
4. Open `googletest-starter-project\build-windows\googletest-starter-project.sln` in Visual Studio 2017
5. Built the `tests` project

The code compiles fine, but gives the `unresolved external symbol` errors shown in the description.

**Comment by claremacrae** [comment]
My only Conan profile, `default`, contains:

```
[build_requires]
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[env]
```

**Comment by claremacrae** [comment]
I was using Conan 1.0.4 - updating to 1.1 and building from scratch didn't help.

**Comment by memsharded** [comment]
The issue is that the CMakeLists.txt is linking with ``${CONAN_LIBS}``:

```cmake
target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```

``cmake_multi`` generator manages both Debug & Release configuration at the same time, defining suffixed variables like ``${CONAN_LIBS_RELEASE}``

You can see how to consume them here: http://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html

**Comment by claremacrae** [comment]
Thanks @memsharded - that gave me the info to fix it.
